---
- block:
    - name: Install Python mysqlclient
      ansible.builtin.apt:
        name: python3-mysqldb
        state: present

    - name: Create MySQL user for zabbix-agent2
      community.mysql.mysql_user:
        name: "{{ mysql_user_for_zbx_agent }}"
        password: "{{ mysql_pass_for_zbx_agent }}"
        host: 'localhost'
        priv: '*.*:SLAVE MONITOR,REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW'
        state: present
      notify: Restart and enable zabbix-agent2

  when: ansible_facts.services['mysql.service'] is defined
